import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useState } from "react";
import { API_URL } from "../utils/urls";
import { twoDecimals } from "../utils/format";
import Carrousel from "../components/Index/Carrousel";

export default function Home({ products }) {
  const [carrouselArray, setCarrouselArray] = useState([
  <Carrousel
    img_url="/uploads/aceite_cbd_820710753f.jpg"
    text1="ACEITE CBD"
    text2="SUB"
    text3="LINGUAL"
    description="Presentamos Oil Hemp nuestro extraordinario Aceite extracto de cáñamo
  de amplio espectro CBD completo puro, directamente de la planta."
    slug="aceite-sublingual"
  />, 
  <Carrousel
    img_url="/uploads/Gomitas_Yellow_2_6ad2691452.png"
    text1="GOMITAS"
    text2="CBD"
    text3=""
    description="Gomitas suaves, fáciles de consumir, brindan dosis consistentes y tienen un sabor delicioso"
    />]);
  const [actualNav, setActualNav] = useState(0)

  const handleNav = (direction) => {
    if(direction === 'right'){
      if(actualNav === carrouselArray.length-1 ){
        setActualNav(0)
      }else{
        setActualNav(actualNav + 1)
      }
    } else {
      if(actualNav === 0 ){
        setActualNav(carrouselArray.length-1)
      }else{
        setActualNav(actualNav - 1)
      }
    }
  }

  return (
    <div>
      <Head>
        <title>Auremp - Enfocate en lo que importa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.carraousel_container}>
          {carrouselArray[actualNav]}
          
        </div>

        <div className={styles.navigation}>
          <div className={styles.left} onClick={()=>handleNav('left')}>
            <Image
              src="/left.png"
              alt="Picture of the author"
              width="100"
              height="100"
            />
          </div>

          <div className={styles.right} onClick={()=>handleNav('right')}>
            <Image
              src="/right.png"
              alt="Picture of the author"
              width="100"
              height="100"
            />
          </div>
        </div>
      </div>

      <div className={styles.popular}>
        <h3>
          Productos para cada <span className="gold_text">estilo</span> de vida
        </h3>
        <div className={styles.products}>
          <div className={styles.card}>
            <div className={styles.img}>
              <Image
                src={`${API_URL}/uploads/aceite_cbd_820710753f.jpg`}
                alt="Picture of the author"
                width="400"
                height="600"
                layout="responsive"
              />
            </div>
            <p className={styles.name}>Aceite Sublingual</p>
          </div>
          <div className={styles.card}>
            <div className={styles.img}>
              <Image
                src={`${API_URL}/uploads/Gomitas_Yellow_2_6ad2691452.png`}
                alt="Picture of the author"
                width="400"
                height="600"
                layout="responsive"
              />
            </div>
            <p className={styles.name}>Gomitas</p>
          </div>
        </div>
      </div>
      <div className={styles.lifestyle}>
        <div className={styles.lifestyle_bg}></div>
        <h3 className={styles.slogan}>
          Enfocate en lo que consideras{" "}
          <span className="gold_text">importante</span>
        </h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nisl,
          donecLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam
          nisl, donec
        </p>
      </div>

      <div className={styles.about}>
        <div className={styles.about_img}>
          <Image src="/about.jpg" layout="fill"></Image>
          <h3>
            Sobre <br></br> Nosotros
          </h3>
        </div>
        <div className={styles.info}>
          <h3 className="gold_text">Mision</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nisl,
            donecLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam
            nisl, donec
          </p>
          <h3 className="gold_text">Vision</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nisl,
            donecLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam
            nisl, donec
          </p>
        </div>
        <div className={styles.about_logo}>
          <Image
            src="/auremp-logo.png"
            alt="Picture of the author"
            layout="fill"
          />
        </div>
      </div>

      <div className={styles.suscribe}>
        <h3>
          Mantente al tanto de las <span className="gold_text">novedades</span>{" "}
        </h3>
        <form>
          <input type="email" placeholder="Juan@correo.com"></input>
          <button className="btn btn-primary">Enviar</button>
        </form>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  //fetch the products
  const product_res = await fetch(`${API_URL}/productos/`);
  const products = await product_res.json();

  //return the products as props
  return {
    props: {
      products, //products: products
    },
  };
}
